### ISSUE TITLE
Reply ussd error in multi steps

### ISSUE THREAD

**Issue by fumant2000** [vkammerer/ussd_service#19]
Hi all. I'm starting a new thread today. I will keep knowing please if you prefer to find a way to reduce this issue of ussd multisessions in flutter. indeed the user will have to confirm thanks to a number, but it is impossible to manage the multi-sessions with your pulgin

**Comment by vkammerer** [comment]
Hi, I don't understand what your issue is, nor if it is an issue.

Please clarify what you mean.

This plugin is only a wrapper over Android's `sendUssdRequest`, and there are known limitations to multi steps USSD request with this API, explained at https://github.com/vkammerer/ussd_service#interactive--multi-steps-ussd-sessions

**Comment by fumant2000** [comment]
Okay thanks for your answer. That was exactly his problem. I wanted to know how to perform USSD queries in several steps (multi-session queries). I went through all the documentation and forums and I didn't find anything interesting

**Comment by vincent-hoodoo** [comment]
Again, I don't understand what your intention is when opening this issue. Please clarify what you want.

**Comment by fumant2000** [comment]
I would like to know if you have found a way to perform multi-session USSD queries

**Comment by vincent-hoodoo** [comment]
Everything there is to know is already in the paragraph I linked to above

**Comment by fumant2000** [comment]
ok
